### ISSUE TITLE
Some teething problems

### ISSUE THREAD

**Issue by deg** [tcw/lein-create-template#2]
Thank you for this template generator! I've been avoiding learning how to create lein templates for a while, figuring it was one too many unshaven yaks for me. This make it so much easier.

But, I'm hitting a few snags. Listing them here as I find them, in the hope that this helps the next newbie (or, at least, me the next time I do this).

1) The readme here should remind the user to really, really, clean the source directory: at least 'lein clean' and (if needed) 'lein cljsbuild clean'.  Also to look for any spurious files, often hidden by .gitignore. Best might often be to pull a clean copy of the repo before generating the template.  This was all obvious to me in theory, but took me a few iterations of head-slap before I paid attention and removed all the junk files.

2) After installing my new template locally, I failed to create a new project with it. I got the error 'Failed to resolve version for <my-template>:lein-template:jar:RELEASE'. This looks very much like https://github.com/technomancy/leiningen/issues/1235, related to having a snapshot version of my project and not yet on Clojars. But, that issue was closed in lein 2.3.4, and I had the problem now in lein 2.5.0.

Nonetheless, the fix at the end of the [discussion cited there](https://groups.google.com/forum/#!topic/pedestal-dev/fM4YAb0yP-E) worked: to create the new project while within the template project. So, looks like that bug, or some variant, is still extant, but the workaround still works.

3) My [project](https://github.com/deg/allergy/commit/a75407d009c4a8bbe80ca6a25658fd8a7371f535) is based on Chestnut and has a fairly complex Clojurescript'y build configuration.  Some files, particularly the profile-dependent env directory, were not included in the template.

(So far, I've worked through (1) and (2). I've not yet tackled (3); probably won't until tomorrow. I'll add to this if I find more snags).

**Comment by deg** [comment]
Ok, finally got back to this after two weeks of distraction. I see that there already is support for template additions, but it came in after the 0.1.1 version that is on Clojars.

I'll put together a pull request that bumps the version and adds some bits to the readme.  Hope to have this ready later today.

**Comment by tcw** [comment]
Thanks!
I have merged the changes.
Sorry for such a late reply.
