### ISSUE TITLE
Name Collisions

### ISSUE THREAD

**Issue by georgewsinger** [tcw/lein-create-template#6]
Great project. I've gotten a lot of utility out of it so far.  A couple of issues/suggested features (seperated into two issues):

1. `lein-create-template` suffers from name collisions: i.e. if your source files contain

`/src/subproject1/core.cljs`
`/src/subproject2/core.cljs`

then only one of these `core.cljs` will be copied through to your template.

**Comment by tcw** [comment]
Solved in 0.2.0.
